### PR TITLE
dm/idem-potent-bump

### LINKED ISSUE #47: Wrong error message when updating dependency
Steps to reproduce:
- `dmenv bump-in-lock --git ci 87817657f2e7731b849353885bd87387bbc92ca5`
- `dmenv bump-in-lock --git ci 87817657f2e7731b849353885bd87387bbc92ca5`

Expected result:
The second command should succeed, or fail saying that ci is already on the right commit

Obtained result:
`Error: 'ci' not found in lock`

### PR DESCRIPTION
**Pull request by dmerejkowsky**
Fix #47

### CODE REVIEW

**Comment by dmerejkowsky** [comment]
Not sure about types there

`Result<Option<String>, ParseError>`  for `bump_func` looks weird, and so does

`Result<(bool,String). Error>` for `bump()`

On the other hand, should I create a custom type (struct or union?) *just* for the return type of these two functions ?

File: src/lock.rs [hunk 1]
```diff
@@ -81,10 +92,10 @@ fn simple_bump(line: &str, name: &str, version: &str) -> Result<String, ParseErr
 
     let dep_name = words[0];
     if dep_name != name {
-        return Ok(line.to_string());
+        return Ok(None);
     }
 
-    Ok(format!("{}=={}", dep_name, version).to_string())
+    Ok(Some(format!("{}=={}", dep_name, version).to_string()))
```
Comment (tux3) [inline src/lock.rs]: You don't need the to_string =]

File: src/lock.rs [hunk 2]
```diff
@@ -108,32 +123,38 @@ impl Lock {
...
+            if let Some(bumped_line) = bumped_line {
+                num_matches += 1;
+                res.push_str(&bumped_line);
+                if bumped_line != line {
+                    changed = true;
+                }
+            } else {
+                res.push_str(line);
+            };
             res.push_str("\n");
```
Comment (tux3) [inline src/lock.rs]: Gratuitous suggestion: Instead of doing push_str twice it's actually a *tiny* bit shorter/more efficient to just use format!:
```
    res = format!("{}\n", bumped_line);
} else {
   res = format!("{}\n", line);
```

(imo format is slightly cooler in general because if this weren't in a for loop you could make res non-mutable!)

File: src/lock.rs [hunk 3]
```diff
@@ -108,32 +123,38 @@ impl Lock {
         name: &str,
         version: &str,
         bump_func: Box<BumpFunc>,
-    ) -> Result<String, Error> {
```
Comment (tux3) [inline src/lock.rs]: Since you can (and do) destructure the result with pretty name whenever you call the function, as far as I'm concerned it's fine not to make a type just for this. 
I think it's kind of a subjective preference, really! Couldn't blame anyone for making a type here.

Comment (dmerejkowsky) [reply src/lock.rs]: Good point. I'll leave it like that then

File: src/lock.rs [hunk 4]
```diff
@@ -108,32 +123,37 @@ impl Lock {
...
+    ) -> Result<(bool, String), Error> {
```
Comment (blastrock) [inline src/lock.rs]: Why the bool and not the Optional<String> like above?
